import type { Metadata, Viewport } from "next";

/**
 * Site-wide metadata for Alkemos.
 *
 * English is the PRIMARY language (targeting English-speaking audience).
 * Arabic is secondary (supported via language toggle).
 *
 * Strategy: Position Alkemos as a comprehensive sports & wellness platform
 * (not just a coaching site). Keywords cover all platform features:
 * exercises, programs, tools, food library, blog.
 */
export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || 'https://alkemos.com'),
  // §12.53 item 5 (2026-09-15, deep audit): was 94 chars — SERP truncates
  // ~60, so the feature tail ("| Exercises, Programs, Calculators &
  // Coaching") never rendered. Shortened to the primary positioning line
  // (47 chars, matches the og:title verbatim — the first keywords the
  // audit required to keep lead the title).
  title: "Alkemos — The Smart Fitness & Nutrition Platform",
  // Phase 117 completion (owner directive 2026-09-04): meta description
  // shortened to 150-160 chars with a clear CTA — the previous 245-char
  // version had no call to action and got truncated by search engines.
  // §12.50-أ-7 (Phase 193): the category line is unified on the owner
  // positioning «the smart, all-in-one fitness & nutrition platform».
  // Phase 194 (owner directive — Copy Refinement Pass): the description
  // now LEADS with the one-platform positioning and keeps the library
  // numbers as proof points instead of a bare feature list.
  description:
    "Train smarter. Eat with precision. Progress with numbers on your side. Alkemos unifies training, nutrition, and AI planning — 868+ exercises, 8,830+ foods, 8 free tools, and the EVO AI coach.",
  keywords: [
    // Platform-level keywords (primary, English) — focused set, one owner
    // per page; tool names belong to their own routes.
    "fitness platform",
    "exercise library",
    "workout programs",
    "food database",
    "free fitness tools",
    "AI fitness coach",
    "online coaching",
    // Arabic cluster (the AR market is standalone, not a translation)
    "منصة لياقة وتغذية",
    "مكتبة تمارين",
    "حاسبة السعرات الحرارية",
    "مخطط وجبات",
    "كوتشينج أونلاين",
    // Brand
    "Alkemos",
  ],
  authors: [{ name: "Alkemos" }],
  manifest: "/manifest.json",
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/icon-32.png", type: "image/png", sizes: "32x32" },
      { url: "/favicon.png", type: "image/png", sizes: "64x64" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Alkemos",
  },
  openGraph: {
    title: "Alkemos — The Smart Fitness & Nutrition Platform",
    description:
      "868+ exercises, 8,830+ foods, 8 free tools, ready programs and diets, an AI coach, and optional human coaching — in Arabic and English.",
    type: "website",
    siteName: "Alkemos",
    locale: "en_US",
    url: "https://alkemos.com",
    images: [
      {
        // PHASE 187 (deep-audit P0-2): branded home OG card (mirrors the
        // /api/og-image design) instead of the raw logo — richer card for
        // homepage/about/contact shares. Generated by
        // scripts/generate-og-cards.py (repo tooling, Pillow + libraqm).
        url: "/images/og/og-home-en.png",
        width: 1200,
        height: 630,
        alt: "Alkemos — The Smart Fitness & Nutrition Platform",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Alkemos — The Smart Fitness & Nutrition Platform",
    description:
      "Training, nutrition, and AI planning in one bilingual platform: 868+ exercises, 8,830+ foods, 8 free tools, and the EVO AI coach.",
    images: ["/images/og/og-home-en.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  verification: {
    google: "v9YnsQ7PMp5EsTOxG9ysrAvWWoWNn0sjzDEJh6Lb7fs",
  },
  // FULL-SITE AUDIT FIX (2026-08-30): the previous alternates block
  // (canonical: homepage + languages en-US/ar-EG) was inherited by EVERY
  // page without its own metadata — /about, /contact, /meal-planner,
  // /privacy, /terms all declared canonical = homepage, telling Google
  // they were duplicates of "/" (deindexing risk). The inherited
  // ar-EG→/ar hreflang also falsely claimed the AR HOMEPAGE was the AR
  // twin of every such page. And the en-US/ar-EG codes conflicted with
  // the en/ar codes every per-page layout declares (mixed codes make
  // Google distrust the whole hreflang cluster).
  //
  // Rule now enforced site-wide: the ROOT metadata declares NO
  // alternates. Each indexable page owns its canonical/hreflang:
  //   - Homepage pair: src/app/(home)/layout.tsx
  //   - Mirror pages:   per-page metadata (homepage AR mirror + Task 3)
  //   - Bilingual one-URL pages (faq, for-coaches): self-canonical in
  //     their own layouts/pages
  //   - Noindex pages (auth, checkout, profile, (app), admin): need no
  //     canonical at all
  category: "Health & Fitness",
};

export const viewport: Viewport = {
  // VRD-V0 (audit C-4): the legacy Apple-blue #0071e3 clashed with the
  // Marble & Chrome identity (zero-blue law). VRD-V1 (owner direction
  // 2026-09-23 «تحسين الهوية الحالية دون تغييرها»): two-value format
  // tracking the REAL theme surfaces — light --bg warm ivory #FAF8F5,
  // dark --bg warm graphite #12100E (globals.css VRD-V1 tokens).
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FAF8F5" },
    { media: "(prefers-color-scheme: dark)", color: "#12100E" },
  ],
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};
