/**
 * GENERATE SEARCH INDEXES — VERCEL-USAGE-3 (2026-09-21).
 *
 * WHY: src/lib/evo-search.ts (the EVO chat context search) imported the
 * FULL data modules:
 *   - src/lib/foods.ts     ~3.6MB  (8,830 foods with servings/tags/fiber…)
 *   - src/lib/exercises.ts ~1.8MB  (868 exercises with 5-8 step instructions
 *                                   + tips in BOTH languages)
 * That dragged ~5.4MB of source into every serverless bundle that imports
 * the chat route (/api/ai/chat), inflating Vercel Functions Storage and
 * forcing V8 to parse megabytes on every chat instance cold start
 * (measured contribution to the Fluid Active CPU overage, 4h33m/4h).
 *
 * The search surface only needs a tiny slice of each record:
 *   - foods:     slug, nameAr, nameEn, category, calories, protein,
 *                carbs, fat (searchFoods + getFoodNutrition fields)
 *   - exercises: slug, nameAr, nameEn, category, equipment,
 *                primaryMuscles, secondaryMuscles
 *
 * This script derives BOTH light indexes from the real data files and
 * re-writes src/lib/foods-search-index.ts + src/lib/exercises-search-index.ts.
 * Re-run after any data change:
 *
 *   bun scripts/generate-search-indexes.ts
 *
 * The generator imports the stripped modules in-memory only — the
 * heavyweight source files are NEVER duplicated into the repo, and the
 * generated files stay the only thing /api/ai/chat bundles.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const GEN_DIR = join(ROOT, "scripts", ".generated");

function stripServerOnly(relPath: string, tmpName: string): string {
  const src = readFileSync(join(ROOT, relPath), "utf8");
  const stripped = src
    .replace('import "server-only";', "")
    .replaceAll(/from "\.\/([a-z-]+)"/g, 'from "@/lib/$1"');
  const out = join(GEN_DIR, tmpName);
  writeFileSync(out, stripped);
  return out;
}

mkdirSync(GEN_DIR, { recursive: true });

// foods.ts — strip the client-guard, reroute type imports, import, project.
const foodsPath = stripServerOnly("src/lib/foods.ts", "foods-stripped.ts");
const { FOODS } = (await import(foodsPath)) as {
  FOODS: Array<{
    slug: string;
    nameAr: string;
    nameEn: string;
    category: string;
    per100g: { calories: number; protein: number; carbs: number; fat: number };
  }>;
};

const exercisesPath = stripServerOnly(
  "src/lib/exercises.ts",
  "exercises-stripped.ts",
);
const { EXERCISES } = (await import(exercisesPath)) as {
  EXERCISES: Array<{
    slug: string;
    nameAr: string;
    nameEn: string;
    category: string;
    equipment: string;
    primaryMuscles: string[];
    secondaryMuscles: string[];
  }>;
};

function lit(v: string): string {
  return JSON.stringify(v);
}

const foodsIndex =
  `/**
 * FOODS SEARCH INDEX — GENERATED FILE, DO NOT EDIT BY HAND.
 *
 * Generated by scripts/generate-search-indexes.ts from src/lib/foods.ts
 * (the full 3.6MB server-only database). Contains ONLY the fields the
 * EVO search surface reads (evo-search.ts): names, category, and the
 * four macro values per 100g. Re-generate after any foods.ts change:
 *
 *   bun scripts/generate-search-indexes.ts
 *
 * VERCEL-USAGE-3: importing this ~1.2MB index instead of the full
 * foods.ts module keeps /api/ai/chat's serverless bundle (and its
 * V8 parse cost) a fraction of the previous size.
 */

export type FoodSearchRow = {
  slug: string;
  nameAr: string;
  nameEn: string;
  category: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
};

export const FOODS_SEARCH_INDEX: FoodSearchRow[] = [
${FOODS.map(
  (f) =>
    `  { slug: ${lit(f.slug)}, nameAr: ${lit(f.nameAr)}, nameEn: ${lit(f.nameEn)}, category: ${lit(f.category)}, calories: ${f.per100g.calories}, protein: ${f.per100g.protein}, carbs: ${f.per100g.carbs}, fat: ${f.per100g.fat} },`,
).join("\n")}
];
`;

const exercisesIndex =
  `/**
 * EXERCISES SEARCH INDEX — GENERATED FILE, DO NOT EDIT BY HAND.
 *
 * Generated by scripts/generate-search-indexes.ts from src/lib/exercises.ts
 * (the full 1.8MB database with bilingual instructions/tips). Contains ONLY
 * the fields the EVO search surface reads (evo-search.ts): names, category,
 * equipment, muscle groups. Re-generate after any exercises.ts change:
 *
 *   bun scripts/generate-search-indexes.ts
 *
 * VERCEL-USAGE-3: importing this ~200KB index instead of the full
 * exercises.ts module keeps /api/ai/chat's serverless bundle (and its
 * V8 parse cost) a fraction of the previous size.
 */

export type ExerciseSearchRow = {
  slug: string;
  nameAr: string;
  nameEn: string;
  category: string;
  equipment: string;
  primaryMuscles: string[];
  secondaryMuscles: string[];
};

export const EXERCISES_SEARCH_INDEX: ExerciseSearchRow[] = [
${EXERCISES.map(
  (e) =>
    `  { slug: ${lit(e.slug)}, nameAr: ${lit(e.nameAr)}, nameEn: ${lit(e.nameEn)}, category: ${lit(e.category)}, equipment: ${lit(e.equipment)}, primaryMuscles: ${JSON.stringify(e.primaryMuscles)}, secondaryMuscles: ${JSON.stringify(e.secondaryMuscles)} },`,
).join("\n")}
];
`;

writeFileSync(join(ROOT, "src/lib/foods-search-index.ts"), foodsIndex);
writeFileSync(join(ROOT, "src/lib/exercises-search-index.ts"), exercisesIndex);

console.log(
  `foods-search-index.ts: ${FOODS.length} rows, ${(foodsIndex.length / 1024).toFixed(0)}KB`,
);
console.log(
  `exercises-search-index.ts: ${EXERCISES.length} rows, ${(exercisesIndex.length / 1024).toFixed(0)}KB`,
);
