import { describe, it, expect } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

/**
 * PHASE 187 — og:image coverage law (deep-audit P0-2).
 * Live audit: the biggest indexable surfaces shared NO social card —
 * exercises (SSG), foods, muscle hubs, collections, tools, blog
 * categories and the AR root (the AR layout declared its own
 * openGraph without images, so every AR page without its own block
 * inherited nothing). Fix: 14 static branded family cards
 * (public/images/og/ — design mirrors /api/og-image, generated by
 * scripts/generate-og-cards.py with the self-hosted Cairo fonts).
 *
 * §12.53 item 4 (2026-09-15, second deep audit): the EN LIST surfaces
 * still shared no card — their layouts/pages declare their own
 * openGraph, which REPLACES the root block in Next.js metadata merging,
 * so nothing was inherited (the AR mirrors inherit og-home-ar from
 * /ar/layout.tsx; the EN side inherited nothing). The same surfaces are
 * now wired: /exercises · /foods · /programs · /coaching · /memberships
 * · /evo · /diet-plan hub + cells · /equipment/* (family cards where a
 * matching one exists — exercises/foods — the home card elsewhere,
 * mirroring the AR inheritance behavior exactly).
 *
 * Batch 1-b (2026-09-16): the SAME replace-not-inherit gap existed on
 * three AR mirrors the batch-1 live verification caught — /ar/evo,
 * /ar/coaching and /ar/diet-plan (hub + 24 cells) declared openGraph
 * without images, so og-home-ar was NOT inherited. All four surfaces are
 * now wired with the home card — exact mirror of the EN fix.
 *
 * Discovery 208 → Phase 209 (2026-09-16, owner order): the EN side of the
 * affiliate pair had the identical gap all along — /affiliate's own
 * openGraph block served no card at all (it wasn't on the item-4 audit
 * list of EN surfaces). og-home-en pinned; both halves of the pair are
 * now guarded.
 *
 * Phase 218 (D-02 — owner deferred-item reopened 2026-09-17): the coach
 * landing pair (EN canonical + AR mirror). noindex pages, but coaches
 * share the URLs DIRECTLY (WhatsApp/X embeds) and the child openGraph
 * block replaces the root card — every share rendered cardless. Home
 * card pinned on both halves.
 *
 * Guarded contracts:
 *   1. Every wired surface references its family og asset in BOTH
 *      openGraph.images and twitter.images.
 *   2. Wired twitter cards are summary_large_image (a "summary" card
 *      ignores images — pointless with a 1200×630 asset).
 *   3. All 14 assets exist on disk.
 *   4. No wired surface regresses to /logo.png.
 */

const OG_DIR = resolve(__dirname, "../../../public/images/og");

const CARDS = [
  "og-home-en", "og-home-ar",
  "og-exercises-en", "og-exercises-ar",
  "og-foods-en", "og-foods-ar",
  "og-hubs-en", "og-hubs-ar",
  "og-collections-en", "og-collections-ar",
  "og-tools-en", "og-tools-ar",
  "og-blog-category-en", "og-blog-category-ar",
  // Phase 231 (owner order C): dedicated cards for the three surfaces
  // that still shared a family card — EVO (was og-home), the for-coaches
  // landing pair (was the vertical 1122×1402 coach-portrait.jpg) and the
  // blog index pair (was the homepage card via inheritance).
  "og-evo-en", "og-evo-ar",
  "og-for-coaches-en", "og-for-coaches-ar",
  "og-blog-en", "og-blog-ar",
] as const;

/** surface source → the family card it must reference */
const WIRED_SURFACES: Array<[string, string]> = [
  // Detail surfaces (Phase 187)
  ["src/app/exercises/[slug]/page.tsx", "og-exercises-en"],
  ["src/app/ar/exercises/[slug]/page.tsx", "og-exercises-ar"],
  ["src/app/foods/[slug]/page.tsx", "og-foods-en"],
  ["src/app/ar/foods/[slug]/page.tsx", "og-foods-ar"],
  ["src/app/muscles/[group]/page.tsx", "og-hubs-en"],
  ["src/app/ar/muscles/[group]/page.tsx", "og-hubs-ar"],
  ["src/app/collections/[slug]/page.tsx", "og-collections-en"],
  ["src/app/ar/collections/[slug]/page.tsx", "og-collections-ar"],
  ["src/app/blog/category/[slug]/page.tsx", "og-blog-category-en"],
  ["src/app/ar/blog/category/[slug]/page.tsx", "og-blog-category-ar"],
  ["src/app/tools/layout.tsx", "og-tools-en"],
  ["src/app/tools/bmi-calculator/layout.tsx", "og-tools-en"],
  ["src/app/tools/body-fat-calculator/layout.tsx", "og-tools-en"],
  ["src/app/tools/calorie-calculator/layout.tsx", "og-tools-en"],
  ["src/app/tools/macro-calculator/layout.tsx", "og-tools-en"],
  ["src/app/tools/water-tracker/layout.tsx", "og-tools-en"],
  ["src/app/ar/tools/layout.tsx", "og-tools-ar"],
  ["src/app/ar/tools/bmi-calculator/layout.tsx", "og-tools-ar"],
  ["src/app/ar/tools/body-fat-calculator/layout.tsx", "og-tools-ar"],
  ["src/app/ar/tools/calorie-calculator/layout.tsx", "og-tools-ar"],
  ["src/app/ar/tools/macro-calculator/layout.tsx", "og-tools-ar"],
  ["src/app/ar/tools/water-tracker/layout.tsx", "og-tools-ar"],
  ["src/app/ar/layout.tsx", "og-home-ar"],
  // EN list surfaces (§12.53 item 4 — a child openGraph block replaces
  // the root one in Next.js merging, so these must pin their own card)
  ["src/app/exercises/layout.tsx", "og-exercises-en"],
  ["src/app/foods/layout.tsx", "og-foods-en"],
  ["src/app/programs/layout.tsx", "og-home-en"],
  ["src/app/coaching/layout.tsx", "og-home-en"],
  ["src/app/memberships/layout.tsx", "og-home-en"],
  ["src/app/evo/layout.tsx", "og-evo-en"],
  ["src/app/diet-plan/page.tsx", "og-home-en"],
  ["src/app/diet-plan/[level]/[system]/page.tsx", "og-home-en"],
  ["src/app/equipment/[type]/page.tsx", "og-home-en"],
  // AR list surfaces (batch 1-b — the same replace-not-inherit gap on
  // the AR side, caught by batch-1 live verification)
  ["src/app/ar/evo/layout.tsx", "og-evo-ar"],
  ["src/app/ar/coaching/layout.tsx", "og-home-ar"],
  ["src/app/ar/diet-plan/page.tsx", "og-home-ar"],
  ["src/app/ar/diet-plan/[level]/[system]/page.tsx", "og-home-ar"],
  // §12.53 item 11 (2026-09-16): the affiliate AR mirror — same gap
  // (its layout declares openGraph, so og-home-ar must be pinned).
  ["src/app/ar/affiliate/layout.tsx", "og-home-ar"],
  // Discovery 208 → Phase 209 (2026-09-16): the EN half of the affiliate
  // pair — same replace-not-inherit gap (see header note).
  ["src/app/affiliate/layout.tsx", "og-home-en"],
  // Phase 216 (P2-1 — deep-audit confirmed-7): the 14 audited surfaces —
  // static AR pages (about/privacy/terms/contact), FAQ ×2, compare ×2,
  // the two AI planners ×2 and the coach-registration pair; the compare
  // + register + AR-equipment twitter cards were "summary" (ignores
  // images) and are now summary_large_image.
  ["src/app/ar/about/page.tsx", "og-home-ar"],
  ["src/app/ar/privacy/page.tsx", "og-home-ar"],
  ["src/app/ar/terms/page.tsx", "og-home-ar"],
  ["src/app/ar/contact/page.tsx", "og-home-ar"],
  ["src/app/faq/page.tsx", "og-home-en"],
  ["src/app/ar/faq/page.tsx", "og-home-ar"],
  ["src/app/compare/page.tsx", "og-home-en"],
  ["src/app/ar/compare/page.tsx", "og-home-ar"],
  ["src/app/ai-meal-planner/layout.tsx", "og-tools-en"],
  ["src/app/ar/ai-meal-planner/layout.tsx", "og-tools-ar"],
  ["src/app/ai-workout-planner/layout.tsx", "og-tools-en"],
  ["src/app/ar/ai-workout-planner/layout.tsx", "og-tools-ar"],
  ["src/app/for-coaches/register/layout.tsx", "og-home-en"],
  ["src/app/ar/for-coaches/register/layout.tsx", "og-home-ar"],
  // Phase 216 (P2-1 discoveries beyond the audit list — same defect
  // class, live-verified missing og:image): the meal-planner pair and
  // the AR equipment hub (twin of the already-wired EN surface).
  ["src/app/meal-planner/layout.tsx", "og-tools-en"],
  ["src/app/ar/meal-planner/layout.tsx", "og-tools-ar"],
  ["src/app/ar/equipment/[type]/page.tsx", "og-home-ar"],
  // Phase 218 (D-02 — owner deferred-item reopened 2026-09-17): the
  // coach-landing pair — noindex, but shared directly by coaches
  // (WhatsApp/X embeds), so a cardless share was the defect (same
  // replace-not-inherit class as every surface above).
  ["src/app/coaches/[slug]/page.tsx", "og-home-en"],
  ["src/app/ar/coaches/[slug]/page.tsx", "og-home-ar"],
  // Phase 231 (owner order C): the for-coaches pair drops the vertical
  // coach-portrait.jpg (1122×1402) for the dedicated horizontal
  // 1200×630 card; the blog index pair stops inheriting the homepage
  // card and pins its own dedicated card.
  ["src/app/for-coaches/layout.tsx", "og-for-coaches-en"],
  ["src/app/ar/for-coaches/layout.tsx", "og-for-coaches-ar"],
  ["src/app/blog/page.tsx", "og-blog-en"],
  ["src/app/ar/blog/page.tsx", "og-blog-ar"],
];

function repoRootPath(rel: string): string {
  return resolve(__dirname, "../../..", rel);
}

describe("og:image coverage (Phase 187 — P0-2)", () => {
  it("all branded family cards exist on disk", () => {
    for (const card of CARDS) {
      const p = resolve(OG_DIR, `${card}.png`);
      expect(existsSync(p), `${card}.png missing (run scripts/generate-og-cards.py)`).toBe(true);
    }
  });

  it.each(WIRED_SURFACES)("%s references its family card in og + twitter", (rel, card) => {
    const src = readFileSync(repoRootPath(rel), "utf8");
    const asset = `/images/og/${card}.png`;
    expect(src).toContain(`url: "${asset}"`);
    expect(src).toContain(`images: ["${asset}"]`);
    expect(src).toContain('card: "summary_large_image"');
    // no regression to the raw logo card
    expect(src).not.toContain('url: "/logo.png"');
  });

  it("the EN root metadata uses the branded home card (not /logo.png)", () => {
    const src = readFileSync(repoRootPath("src/app/metadata.ts"), "utf8");
    expect(src).toContain('url: "/images/og/og-home-en.png"');
    expect(src).not.toContain('url: "/logo.png"');
  });

  it("the generator lives in repo tooling with timeless copy (no library counts)", () => {
    const p = repoRootPath("scripts/generate-og-cards.py");
    expect(existsSync(p)).toBe(true);
    const gen = readFileSync(p, "utf8");
    // PNG text is un-greppable and un-guardable once baked — the BAKED copy
    // (the SPECS entries) must stay count-free (868/8830 change as the
    // library grows). The rule's docstring may mention the numbers.
    const specs = gen.slice(gen.indexOf("SPECS = ["));
    expect(specs).not.toMatch(/868/);
    expect(specs).not.toMatch(/8830/);
  });
});
