import { describe, it, expect } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

/**
 * PHASE 187 — og:image coverage law (deep-audit P0-2).
 * Live audit: the biggest indexable surfaces shared NO social card —
 * exercises (SSG), foods, muscle hubs, collections, tools, blog
 * categories and the AR root (the AR layout declared its own
 * openGraph without images, so every AR page without its own block
 * inherited nothing). Fix: 14 static branded family cards
 * (public/images/og/ — design mirrors /api/og-image, generated by
 * scripts/generate-og-cards.py with the self-hosted Cairo fonts).
 *
 * Guarded contracts:
 *   1. Every wired surface references its family og asset in BOTH
 *      openGraph.images and twitter.images.
 *   2. Wired twitter cards are summary_large_image (a "summary" card
 *      ignores images — pointless with a 1200×630 asset).
 *   3. All 14 assets exist on disk.
 *   4. No wired surface regresses to /logo.png.
 */

const OG_DIR = resolve(__dirname, "../../../public/images/og");

const CARDS = [
  "og-home-en", "og-home-ar",
  "og-exercises-en", "og-exercises-ar",
  "og-foods-en", "og-foods-ar",
  "og-hubs-en", "og-hubs-ar",
  "og-collections-en", "og-collections-ar",
  "og-tools-en", "og-tools-ar",
  "og-blog-category-en", "og-blog-category-ar",
] as const;

/** surface source → the family card it must reference */
const WIRED_SURFACES: Array<[string, string]> = [
  ["src/app/exercises/[slug]/page.tsx", "og-exercises-en"],
  ["src/app/ar/exercises/[slug]/page.tsx", "og-exercises-ar"],
  ["src/app/foods/[slug]/page.tsx", "og-foods-en"],
  ["src/app/ar/foods/[slug]/page.tsx", "og-foods-ar"],
  ["src/app/muscles/[group]/page.tsx", "og-hubs-en"],
  ["src/app/ar/muscles/[group]/page.tsx", "og-hubs-ar"],
  ["src/app/collections/[slug]/page.tsx", "og-collections-en"],
  ["src/app/ar/collections/[slug]/page.tsx", "og-collections-ar"],
  ["src/app/blog/category/[slug]/page.tsx", "og-blog-category-en"],
  ["src/app/ar/blog/category/[slug]/page.tsx", "og-blog-category-ar"],
  ["src/app/tools/layout.tsx", "og-tools-en"],
  ["src/app/tools/bmi-calculator/layout.tsx", "og-tools-en"],
  ["src/app/tools/body-fat-calculator/layout.tsx", "og-tools-en"],
  ["src/app/tools/calorie-calculator/layout.tsx", "og-tools-en"],
  ["src/app/tools/macro-calculator/layout.tsx", "og-tools-en"],
  ["src/app/tools/water-tracker/layout.tsx", "og-tools-en"],
  ["src/app/ar/tools/layout.tsx", "og-tools-ar"],
  ["src/app/ar/tools/bmi-calculator/layout.tsx", "og-tools-ar"],
  ["src/app/ar/tools/body-fat-calculator/layout.tsx", "og-tools-ar"],
  ["src/app/ar/tools/calorie-calculator/layout.tsx", "og-tools-ar"],
  ["src/app/ar/tools/macro-calculator/layout.tsx", "og-tools-ar"],
  ["src/app/ar/tools/water-tracker/layout.tsx", "og-tools-ar"],
  ["src/app/ar/layout.tsx", "og-home-ar"],
];

function repoRootPath(rel: string): string {
  return resolve(__dirname, "../../..", rel);
}

describe("og:image coverage (Phase 187 — P0-2)", () => {
  it("all 14 branded family cards exist on disk", () => {
    for (const card of CARDS) {
      const p = resolve(OG_DIR, `${card}.png`);
      expect(existsSync(p), `${card}.png missing (run scripts/generate-og-cards.py)`).toBe(true);
    }
  });

  it.each(WIRED_SURFACES)("%s references its family card in og + twitter", (rel, card) => {
    const src = readFileSync(repoRootPath(rel), "utf8");
    const asset = `/images/og/${card}.png`;
    expect(src).toContain(`url: "${asset}"`);
    expect(src).toContain(`images: ["${asset}"]`);
    expect(src).toContain('card: "summary_large_image"');
    // no regression to the raw logo card
    expect(src).not.toContain('url: "/logo.png"');
  });

  it("the EN root metadata uses the branded home card (not /logo.png)", () => {
    const src = readFileSync(repoRootPath("src/app/metadata.ts"), "utf8");
    expect(src).toContain('url: "/images/og/og-home-en.png"');
    expect(src).not.toContain('url: "/logo.png"');
  });

  it("the generator lives in repo tooling with timeless copy (no library counts)", () => {
    const p = repoRootPath("scripts/generate-og-cards.py");
    expect(existsSync(p)).toBe(true);
    const gen = readFileSync(p, "utf8");
    // PNG text is un-greppable and un-guardable once baked — the BAKED copy
    // (the SPECS entries) must stay count-free (868/8830 change as the
    // library grows). The rule's docstring may mention the numbers.
    const specs = gen.slice(gen.indexOf("SPECS = ["));
    expect(specs).not.toMatch(/868/);
    expect(specs).not.toMatch(/8830/);
  });
});
